from fpdf import FPDF
from datetime import datetime

class PDF(FPDF):
    def header(self):
        self.set_font("Arial", 'B', 14)
        self.set_text_color(0, 0, 128)
        self.cell(0, 10, "AI Disease Prediction Report", ln=True, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", 'I', 9)
        self.set_text_color(128)
        self.cell(0, 10, "Generated by MedPredict AI - for informational purposes only", align='C')

def create_report(user_name, symptoms_list, predicted_disease):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)
    pdf.set_text_color(0)

    # Patient Info
    pdf.cell(0, 10, f"Name: {user_name}", ln=True)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(5)

    # Symptoms
    pdf.set_fill_color(230, 230, 250)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Symptoms Provided", ln=True, fill=True)
    pdf.set_font("Arial", size=11)
    for symptom in symptoms_list:
        pdf.cell(0, 8, f"- {symptom}", ln=True)

    # Prediction
    pdf.ln(8)
    pdf.set_fill_color(255, 230, 230)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Predicted Disease", ln=True, fill=True)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 12, predicted_disease, ln=True)

    # Disclaimer
    pdf.set_text_color(0)
    pdf.ln(10)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 8, "Disclaimer: This prediction is based on symptom patterns using a machine learning model. Always consult a licensed medical professional for diagnosis and treatment.")

    # Save file
    filename = f"report_{user_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = f"static/reports/{filename}"
    pdf.output(filepath)

    return filepath
